//
//  ADIFParserTests.swift
//  FullDuplexTests
//
//  Created by Jay Vana on 1/20/26.
//

import XCTest
@testable import FullDuplex

final class ADIFParserTests: XCTestCase {
    func testParseSimpleRecord() throws {
        let adif = "<call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>"

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertEqual(records.count, 1)
        XCTAssertEqual(records[0].callsign, "W1AW")
        XCTAssertEqual(records[0].band, "20m")
        XCTAssertEqual(records[0].mode, "CW")
    }

    func testParseMultipleRecords() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>
        <call:4>K3LR <band:3>40m <mode:3>SSB <qso_date:8>20240115 <time_on:4>1445 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertEqual(records.count, 2)
        XCTAssertEqual(records[0].callsign, "W1AW")
        XCTAssertEqual(records[1].callsign, "K3LR")
        XCTAssertEqual(records[1].mode, "SSB")
    }

    func testParseWithHeader() throws {
        let adif = """
        Generated by Test App
        <adif_ver:5>3.1.4
        <programid:8>TestApp
        <eoh>
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertEqual(records.count, 1)
        XCTAssertEqual(records[0].callsign, "W1AW")
    }

    func testParseTimestamp() throws {
        let adif = "<call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 <eor>"

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertNotNil(records[0].timestamp)

        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm"
        formatter.timeZone = TimeZone(identifier: "UTC")

        XCTAssertEqual(formatter.string(from: records[0].timestamp!), "2024-01-15 14:30")
    }

    func testParsePOTAFields() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 \
        <sig_info:6>K-1234 <my_gridsquare:6>FN31pr <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertEqual(records[0].sigInfo, "K-1234")
        XCTAssertEqual(records[0].myGridsquare, "FN31pr")
    }

    func testParseMySigInfo() throws {
        // my_sig_info is YOUR park reference (activations), sig_info is THEIR park (hunter contacts)
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <time_on:4>1430 \
        <my_sig_info:6>K-5678 <sig_info:6>K-1234 <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        XCTAssertEqual(records[0].mySigInfo, "K-5678") // Activation park
        XCTAssertEqual(records[0].sigInfo, "K-1234") // Hunter contact park
    }

    func testSkipsInvalidRecords() throws {
        let adif = """
        <call:4>W1AW <band:3>20m <mode:2>CW <qso_date:8>20240115 <eor>
        <band:3>40m <mode:3>SSB <eor>
        <call:4>K3LR <band:3>40m <mode:3>SSB <eor>
        """

        let parser = ADIFParser()
        let records = try parser.parse(adif)

        // Second record missing callsign, should be skipped
        XCTAssertEqual(records.count, 2)
        XCTAssertEqual(records[0].callsign, "W1AW")
        XCTAssertEqual(records[1].callsign, "K3LR")
    }
}
